name: Build and publish

on:
  push:
    branches: [ main ]

jobs:
  BuildAndPush:
    runs-on: ubuntu-latest
    name: Build and Push
    steps:
      - name: Checkout 
        uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and push API Server
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: ghcr.io/wa2g07/turnstile-service:${{ github.sha }}, ghcr.io/wa2g07/turnstile-service:latest
  DeploymentTrigger:
    runs-on: ubuntu-latest
    name: Deployment Trigger
    needs:
      - BuildAndPush
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.DEVOPSDISPATCHTOKEN }}
          event-type: turnstileservice-event
          client-payload: '{"ref": "${{ github.ref }}", "tag": "${{ github.sha }}"}'
          repository: wa2g07/FinalProject-DevOps
